#!/bin/bash
# MOAB/Torque submission script for GPC
#
#PBS -l nodes=1:ppn=8,walltime=2:00:00
#PBS -N CUBE

# DIRECTORY TO RUN - $PBS_O_WORKDIR is directory job was submitted from
cd $PBS_O_WORKDIR

# EXECUTION COMMAND; -np = nodes*ppn

cd ../utilities/
source module_load_intel.sh
cafrun  -N 1 ./ic.x > ../batch/many/log_ic1536

cd ../main/
#cafrun  -N 1 ./cafcube.x > ../batch/many/log_cube1536
#mpirun -np 1 ./cafcube.x > ../batch/many/log_cube1536


cd ../batch/
