#!/bin/bash
# MOAB/Torque submission script for Sandy
#
#PBS -l nodes=1:ppn=16,walltime=15:00:00
#PBS -N CUBE
#PBS -q sandy

# DIRECTORY TO RUN - $PBS_O_WORKDIR is directory job was submitted from
cd $PBS_O_WORKDIR

# EXECUTION COMMAND; -np = nodes*ppn

cd ../utilities/
source module_load_intel.sh
cafrun -np 1 -N 1 ./ic.x > ../batch/many/log_ic_1536

cd ../main/
cafrun -np 1 -N 1 ./cafcube.x > ../batch/many/log_cube1536

cd ../batch/
